// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A slang identification AI agent.
 *
 * - identifySlang - A function that handles the slang identification process.
 * - IdentifySlangInput - The input type for the identifySlang function.
 * - IdentifySlangOutput - The return type for the identifySlang function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const IdentifySlangInputSchema = z.object({
  text: z.string().describe('The text to identify slang in.'),
});
export type IdentifySlangInput = z.infer<typeof IdentifySlangInputSchema>;

const IdentifySlangOutputSchema = z.array(
  z.object({
    term: z.string().describe('The slang term identified.'),
    startIndex: z.number().describe('The starting index of the slang term in the text.'),
    endIndex: z.number().describe('The ending index of the slang term in the text.'),
    meaning: z.string().describe('The meaning of the slang term.'),
    briefDefinition: z.string().describe('A very brief (one sentence) definition of the slang term.'),
    countryOfOrigin: z.string().describe('The country of origin of the slang term.'),
    estimatedAgeRange: z.string().describe('The estimated age range of people who use the slang term.'),
  })
);

export type IdentifySlangOutput = z.infer<typeof IdentifySlangOutputSchema>;

export async function identifySlang(input: IdentifySlangInput): Promise<IdentifySlangOutput> {
  return identifySlangFlow(input);
}

const identifySlangPrompt = ai.definePrompt({
  name: 'identifySlangPrompt',
  input: {schema: IdentifySlangInputSchema},
  output: {schema: IdentifySlangOutputSchema},
  prompt: `You are an expert in identifying slang terms in text.

  Given the following text, identify any slang terms and provide their meaning, country of origin, and estimated age range.

  Return a JSON array of objects, where each object represents a slang term found in the text. Each object should have the following properties:

  - term: The slang term itself.
  - startIndex: The starting index of the slang term in the text.
  - endIndex: The ending index of the slang term in the text.
  - meaning: The meaning of the slang term.
  - briefDefinition: A very brief (one sentence) definition of the slang term.
  - countryOfOrigin: The country of origin of the slang term.
  - estimatedAgeRange: The estimated age range of people who use the slang term.

  Text: {{{text}}}
  `,
});

const identifySlangFlow = ai.defineFlow(
  {
    name: 'identifySlangFlow',
    inputSchema: IdentifySlangInputSchema,
    outputSchema: IdentifySlangOutputSchema,
  },
  async input => {
    const {output} = await identifySlangPrompt(input);
    return output!;
  }
);
